name: tests

on:
  push:
  pull_request:

# TODO: Check different standards?
# TODO: Re-enable testing in release

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, clang++-14]
        target: [Debug]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           sudo apt install gcc-10 g++-10 libgcc-10-dev
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DLIBASSERT_BUILD_TESTING=On
           make -j
    - name: test
      working-directory: build
      run: |
           CTEST_OUTPUT_ON_FAILURE=1 make test
  test-macos:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-12, clang++]
        c_compiler: [gcc-12, clang]
        target: [Debug]
        exclude: # TODO: Ugly hack
          - compiler: g++-12
            c_compiler: clang
          - compiler: clang++
            c_compiler: gcc-12
          - compiler: clang++ # Disabled due to #15 TODO TODO TODO
            target: Debug
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_C_COMPILER=${{matrix.c_compiler}} \
            -DLIBASSERT_BUILD_TESTING=On
           make -j
    - name: test
      working-directory: build
      run: |
           CTEST_OUTPUT_ON_FAILURE=1 make test
  test-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler: [cl, clang++]
        target: [Debug]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: dependencies
      run: |
           pip install icdiff
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DLIBASSERT_BUILD_TESTING=On
           msbuild .\libassert.sln
    - name: test
      working-directory: build
      run: |
           ctest -C ${{matrix.target}} --output-on-failure
  test-mingw:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        target: [Debug]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: dependencies
      run: |
           pip install icdiff
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DLIBASSERT_BUILD_TESTING=On `
            "-GUnix Makefiles"
           make -j
    - name: test
      working-directory: build
      run: |
           $env:CTEST_OUTPUT_ON_FAILURE=1
           make test
