#ifndef LIBMMAP__COMPILE_INFO_H
#define LIBMMAP__COMPILE_INFO_H

#if defined(NDEBUG)
#undef LIBMMAP_IS_DEBUG
#undef LIBMMAP_IS_RELEASE
#define LIBMMAP_IS_RELEASE 1
#else
#undef LIBMMAP_IS_DEBUG
#undef LIBMMAP_IS_RELEASE
#define LIBMMAP_IS_DEBUG 1
#endif

#undef LIBMMAP_IS_OPTIMIZED
#if defined(__OPTIMIZE__)
#define LIBMMAP_IS_OPTIMIZED 1
#if LIBMMAP_IS_DEBUG
#define LIBMMAP_IS_OPTIMIZED_DEBUG 1
#else
#define LIBMMAP_IS_OPTIMIZED_RELEASE1
#endif
#else
#define LIBMMAP_IS_DEBUG_OR_UNOPTIMIZED_RELEASE 1
#if LIBMMAP_IS_DEBUG
#define LIBMMAP_IS_UNOPTIMIZED_DEBUG 1
#else
#define LIBMMAP_IS_UNOPTIMIZED_RELEASE 1
#endif
#endif

#endif // LIBMMAP__COMPILE_INFO_H
